apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pp-data
  namespace: ForestFires
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs