apiVersion: v1
kind: Service
metadata:
  name: preprocess-db-service
  labels:
    app: preprocess-db
  namespace: forestfire
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
  selector:
    app: preproces-db