apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: preprocess-db
  name: preprocess-db
  namespace: forestfire
spec:
  replicas: 2 # Creating two PODs for our app
  selector:
    matchLabels:
      app: preprocess-db
  template:
    metadata:
      labels:
        app: preprocess-db
    spec:
      containers:
      - image: gcr.io/weighty-flag-288919/preprocess:0.0.1 # Docker image name, that we pushed to GCR NOTE:ROMARS DE PROJECT
        name: preprocess-db-api     # POD name
        volumeMounts:
        - mountPath: /usr/src/pptdb
          name: preprocess-db-vol
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: PP_LOC
          value: /usr/src/pptdb/
        - name: TRAIN_DB_API
          value: http://training-db-service:5001/training-db/fires
      volumes:
      - name: preprocess-db-vol
        persistentVolumeClaim:
          claimName: nfs-pp-data