apiVersion: v1
kind: Service
metadata:
  name: training-db-service
  labels:
    app: training-db
  namespace: ForestFires
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: training-db