apiVersion: v1
kind: Service
metadata:
  name: visualize-service
  labels:
    app: visualize
  namespace: forestfire
spec:
  type: LoadBalancer
  ports:
  - port: 5004
    targetPort: 5000
  selector:
    app: visualize